### ISSUE TITLE
Auth Code Review

### ISSUE THREAD

**Issue by roryphair** [roryphair/Disagree#2]
I am requesting a code review of my Auth mvp, thank you.

**Comment by kkossally** [comment]
- Overall, great styling and progress through the features. Discord is difficult, as you've discovered, but I have no doubt that you're up to the task.

- [ ] There's a bit of a delay on the demo login.

- [ ] Submitting the session forms with enter works but generates a console error.

- [ ] spacing issues: 
      1. put some space between the top of the viewport and the header
      2. put some space between the buttons and the images
      3. the login and register forms are a little too tall and a little off-center

- [ ] full list of servers only appears after clicking on one of them

- Nice work on the template. I have a good idea of where everything will eventually go. Make sure to review the percentages that each component should take up to match the original site.

- Nice work on the chat!

- It's all coming together. Keep it up!

**Comment by roryphair** [comment]
I am unable to recreate the error with hitting enter on the session forms. Maybe I already fixed it somehow, but can you tell me if you still get it?
